#pragma once

#include <compare>
#include <cstdint>
#include <string>
#include <string_view>
#include <vector>

#include "rc/digest.hpp"
#include "rc/identity.hpp"
#include "rc/lifecycle.hpp"
#include "rc/outcome.hpp"
#include "rc/upstream.hpp"

namespace rc {

// The complete transition-step vocabulary of Route Convergence 1.0.0.  These are
// control-plane route-state transitions, expressed with role names relative to
// the plan: "new" always means the plan target state and "old" always means the
// plan source state.  A rollback plan is an ordinary convergence plan whose
// target state happens to be the state that is being restored, so the same
// vocabulary describes it exactly.  No hardware-specific command exists here:
// Route Convergence 1.0.0 never programmes a switch.
enum class StepKind : std::uint32_t {
  VALIDATE_TARGET = 1,
  PREPARE_NEW_STATE = 2,
  INSTALL_NEW_GROUP = 3,
  INSTALL_NEW_ROUTE = 4,
  ACTIVATE_NEW_PATH = 5,
  VERIFY_NEW_STATE = 6,
  DEACTIVATE_OLD_PATH = 7,
  WITHDRAW_OLD_ROUTE = 8,
  VERIFY_REMOVAL = 9,
  FINALIZE = 10,
};

inline constexpr std::uint32_t kStepKindCount = 10;

[[nodiscard]] std::string_view to_string(StepKind kind) noexcept;

// Read-only step: it observes and reports, it changes no authoritative state.
[[nodiscard]] bool is_observation_step(StepKind kind) noexcept;
// Verification step: an observation step generated by VerificationMode::REQUIRED.
[[nodiscard]] bool is_verification_step(StepKind kind) noexcept;
// Make-side step: it establishes or activates the plan target state.
[[nodiscard]] bool is_make_step(StepKind kind) noexcept;
// Break-side step: it removes or deactivates the plan source state.
[[nodiscard]] bool is_break_step(StepKind kind) noexcept;

// What undoing a completed step would require.  This is a classification, not a
// promise: IRREVERSIBLE steps make a rollback plan impossible to generate, and
// that is reported instead of being papered over.
enum class Reversibility : std::uint32_t {
  // The step is an observation.  Undoing it means nothing.
  OBSERVATION = 1,
  // The step's external effect can be compensated by a generated step.
  COMPENSATABLE = 2,
  // The step's external effect cannot be undone by any generated step.
  IRREVERSIBLE = 3,
};

[[nodiscard]] std::string_view to_string(Reversibility reversibility) noexcept;

// Conflict domains.  Two steps in the same execution layer may run in parallel
// only when they do not touch the same (domain, subject) pair; Route Convergence
// refuses a plan whose executable layer violates that.
enum class ConflictDomain : std::uint32_t {
  NONE = 0,
  ROUTE_TABLE = 1u << 0,
  PATH_STATE = 1u << 1,
  GROUP_STATE = 1u << 2,
  TARGET_STATE = 1u << 3,
};

[[nodiscard]] std::string_view to_string(ConflictDomain domain) noexcept;

// Semantic step key: the identity of a step inside one plan, independent of
// arrival order and memory address.  Canonical ordering is (kind, subject).
struct StepKey {
  StepKind kind = StepKind::VALIDATE_TARGET;
  SubjectToken subject;

  [[nodiscard]] std::string render() const;

  friend auto operator<=>(const StepKey&, const StepKey&) noexcept = default;
  friend bool operator==(const StepKey&, const StepKey&) noexcept = default;
};

// Complete declarative description of one transition step.  Two plans built from
// the same source state, target state, policy and dependency generations contain
// exactly the same StepSpec values in exactly the same canonical order, which is
// what makes the plan digest reproducible.
struct StepSpec {
  StepKind kind = StepKind::VALIDATE_TARGET;
  SubjectToken subject;
  Reversibility reversibility = Reversibility::COMPENSATABLE;
  std::uint32_t conflict_domains = 0;
  // A mandatory step must be COMPLETED (or SKIPPED by explicit governance)
  // before the plan may complete.
  bool mandatory = true;
  // Whether the operation may be retried after a RETRYABLE_FAILURE.  Only
  // declared-idempotent steps are ever retried, and AMBIGUOUS outcomes are never
  // retried at all.
  bool idempotent = true;
  bool verification = false;
  // Exact entity bindings.  A step binds the exact upstream generations it was
  // planned against; a later generation makes the step stale.
  PathId path;
  PathAuthorityGeneration path_authority_generation;
  RouteId route;
  RouteGeneration route_generation;
  MultipathSetId multipath_set;
  MultipathSetGeneration multipath_generation;
  ECMPGroupId ecmp_group;
  ECMPGroupGeneration ecmp_generation;
  AssignmentGeneration assignment_generation;
  WeightedPathSetId weighted_set;
  WeightPolicyGeneration weight_policy_generation;
  // Prerequisites, expressed by semantic key.
  std::vector<StepKey> depends_on;

  [[nodiscard]] StepKey key() const { return StepKey{kind, subject}; }
};

// Structured result of one external operation performed by a worker.  Never a
// bool: APPLIED and IDEMPOTENT are different facts, and AMBIGUOUS is a fact that
// a bool cannot express at all.
enum class BackendOutcome : std::uint32_t {
  APPLIED = 1,
  IDEMPOTENT = 2,
  RETRYABLE_FAILURE = 3,
  PERMANENT_FAILURE = 4,
  AMBIGUOUS = 5,
  UNSUPPORTED = 6,
  STALE = 7,
};

[[nodiscard]] std::string_view to_string(BackendOutcome outcome) noexcept;
[[nodiscard]] bool is_backend_success(BackendOutcome outcome) noexcept;

// Completion must not be a naked boolean.  Every completion binds the plan, the
// exact step generation, the execution attempt, the worker boot and epoch that
// performed it, the structured backend outcome, the state generation the backend
// observed, and the dispatch watermark the work started under.  The evidence
// identity is derived from that content, so an exact replay of the same
// completion produces the same identity and is recognised as idempotent.
struct CompletionEvidence {
  CompletionEvidenceId id;
  ConvergencePlanId plan;
  TransitionStepId step;
  TransitionStepGeneration step_generation;
  MutationAttemptId attempt;
  CoordinatorEpoch epoch;
  PublisherId publisher;
  WorkerBootId worker_boot;
  BackendOutcome outcome = BackendOutcome::APPLIED;
  RouteGeneration applied_route_generation;
  PathAuthorityGeneration observed_path_authority_generation;
  ConvergenceGeneration dispatch_watermark;
  std::string detail;

  [[nodiscard]] bool is_well_formed() const noexcept;
};

// Runtime record of one step.  Step state is never reduced to a bool.
struct TransitionStep {
  TransitionStepId id;
  StepSpec spec;
  TransitionStepGeneration generation = TransitionStepGeneration::from_value(1);
  StepLifecycle state = StepLifecycle::PENDING;
  std::uint32_t attempts = 0;
  CompletionEvidenceId last_evidence;
  MutationAttemptId last_attempt;
  ConvergenceGeneration dispatch_watermark;
  CoordinatorEpoch dispatch_epoch;
  PublisherId dispatch_publisher;
  WorkerBootId dispatch_boot;
  ChangeReason last_change = ChangeReason::CREATE;
  ConditionCode last_condition = ConditionCode::NONE;
  // Set on rollback-plan steps: the forward step this step compensates.
  TransitionStepId compensates;

  [[nodiscard]] bool is_executable() const noexcept { return state == StepLifecycle::READY; }
  [[nodiscard]] bool is_satisfied() const noexcept { return is_step_satisfied(state); }
};

// Deterministic identity derivations.  These are content addresses, not
// counters: the same semantic content always yields the same identity, and no
// identity depends on arrival order or memory address.
[[nodiscard]] ConvergencePlanId derive_plan_id(const struct PlanKey& key, const Digest& content);
[[nodiscard]] TransitionStepId derive_step_id(ConvergencePlanId plan, const StepKey& key);
[[nodiscard]] CompletionEvidenceId derive_evidence_id(const CompletionEvidence& evidence);

}  // namespace rc
